# Generated by Django 5.2.1 on 2025-05-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_locale', models.CharField(max_length=150)),
                ('indirizzo', models.TextField()),
                ('partita_iva', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_contatto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('tipo', models.CharField(choices=[('persona', 'Persona'), ('locale', 'Locale')], max_length=20)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('data_evento', models.DateField()),
                ('orario_evento', models.TimeField()),
                ('luogo', models.CharField(max_length=255)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('posti_disponibili', models.IntegerField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locale')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.utente')),
            ],
        ),
        migrations.AddField(
            model_name='locale',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.utente'),
        ),
    ]
