# Generated by Django 5.2.1 on 2025-05-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_utente_password_hash_utente_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('data_evento', models.DateField()),
                ('orario_evento', models.TimeField()),
                ('luogo', models.CharField(max_length=255)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('posti_disponibili', models.IntegerField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locale')),
            ],
        ),
    ]
