# Generated by Django 5.2.1 on 2025-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
