# Generated by Django 5.2.1 on 2025-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_utente_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locale',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
