# Generated by Django 5.2.1 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_locale_latitudine_locale_longitudine'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='persona',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('O', 'Altro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='situazione_sentimentale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
