# Generated by Django 5.2.1 on 2025-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_locale_profile_image_persona_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='telefono_contatto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
