# Generated by Django 5.2.1 on 2025-08-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_locale_telefono_contatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='last_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_loc_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
