# Generated by Django 5.2.1 on 2025-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_persona_last_accuracy_persona_last_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
