# Generated by Django 5.2.1 on 2025-08-21 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_persona_last_lat_alter_persona_last_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='hidden_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Campi del profilo che il locale vuole NASCONDERE', size=None),
        ),
        migrations.AddField(
            model_name='persona',
            name='hidden_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Campi del profilo che l'utente vuole NASCONDERE", size=None),
        ),
    ]
