# Generated by Django 5.2.1 on 2025-08-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_locale_hidden_fields_persona_hidden_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='locandina',
            field=models.ImageField(blank=True, null=True, upload_to='locandine/'),
        ),
    ]
