# Generated by Django 5.2.1 on 2025-08-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_evento_locandina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='luogo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='posti_disponibili',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
