# Generated by Django 5.2.1 on 2025-08-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_evento_luogo_alter_evento_posti_disponibili_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='luogo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='posti_disponibili',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
