# Generated by Django 5.2.1 on 2025-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_evento_descrizione_alter_evento_luogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='altre_informzioni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='informazioni_utili',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='programma',
            field=models.TextField(blank=True, null=True),
        ),
    ]
