# Generated by Django 5.2.1 on 2025-08-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_evento_altre_informzioni_evento_informazioni_utili_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event'], name='api_eventli_event_i_12a769_idx'), models.Index(fields=['user', 'event'], name='api_eventli_user_id_3e4ff6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_like')],
            },
        ),
    ]
