# Generated by Django 5.2.1 on 2025-08-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_eventlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='altre_informzioni',
            new_name='altre_informazioni',
        ),
    ]
