# Generated by Django 5.2.1 on 2025-09-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_altre_informzioni_evento_altre_informazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='copertina_img',
            field=models.ImageField(blank=True, null=True, upload_to='copertine/'),
        ),
    ]
