# Generated by Django 5.2.1 on 2025-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_evento_copertina_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='prova_campo_nuovo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
