# Generated by Django 5.2.1 on 2025-09-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_evento_prova_campo_nuovo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='prova_campo_nuovo',
        ),
    ]
